spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  application:
    name: book-service
  config:
    import:
      - optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: hml

server:
  port: 8100

resilience4j:
  ratelimiter:
    instancer:
      default:
        limit-for-period: 2
  retry:
    instances:
      foo-bar:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
      default:
        max-attempts: 3


springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs


logging:
  file:
    name: application.log
  level:
    root: INFO