version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=batchDB
      - MYSQL_ROOT_PASSWORD="toor@123"
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - '3306:3306'
    command: --bind-address=0.0.0.0
volumes:
  mysql-volume:
    driver: local
