spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  application:
    name: cambio-service
  config:
    import:
      - optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: hml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka