server:
  port: 8080
spring:
  application:
    name: "greeting-service"
  config:
    import:
      - optional:config-server:http://localhost:8888
  cloud:
    config:
      profile: hml
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
